{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dentacrm.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dentacrm.api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "dentacrm.api.selectorLabels" . | nindent 6 }}
{{- end }}
