apiVersion: v2
name: dentacrm
description: DentraCRM - Multi-Tenant Lead Management SaaS for Dental Clinics
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - dental
  - crm
  - lead-management
  - multi-tenant
  - saas
maintainers:
  - name: Siru
    email: admin@dentacrm.in
dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
